## 实现测试分配到指定节点组，每个节点组一个pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - ng1
                      - ng2
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: eks.amazonaws.com/nodegroup    # 使用上面的 key
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: test
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80

