apiVersion: v1
kind: Service
metadata:
  name: ch-keeper
  namespace: clickhouse
spec:
  clusterIP: None
  ports:
    - name: client
      port: 9181
      protocol: TCP
      targetPort: 9181
    - name: raft
      port: 9234
      protocol: TCP
      targetPort: 9234
  selector:
    app: ch-keeper
  sessionAffinity: None
  type: ClusterIP
