apiVersion: v1
kind: Service
metadata:
  name: ch-server
  namespace: clickhouse
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8123
      protocol: TCP
      targetPort: 8123
    - name: native
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: ch-server
  sessionAffinity: None
  type: ClusterIP
