---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: logger
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-key
  namespace: logger
data:
  encryptedSavedObjects.key: NTkwZGM0MWVmMDMxMTQzOGQ4MjA2YTYxNDdjN2U5ZjI=
  reporting.key: Y2IwZmYwMWZiNDBjYzE2ODgyYmFjNDhiOTU5ZDZkYWM=
  security.key: N2I4ODFlYjcxMzBkNjE4YjZmNjAwYmZjMTgzZmMxMzI=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: kibana
  name: kibana
  namespace: logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kibana-new
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: eks.amazonaws.com/nodegroup
                    operator: In
                    values:
                      - InfraGroup
      containers:
        - env:
            - name: ELASTICSEARCH_URL
              value: https://ip:9200
            - name: ELASTICSEARCH_SERVICEACCOUNTTOKEN
              value: "AAEAAWVsYXN0aWMva2liYW5hL215LWtpYmFuYS10b2tlbjpTWXZHREpEVFQ4MmtUMHh6aXluTXh3"
            - name: SERVER_BASEPATH
              value: /kibana
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: none
            - name: SERVER_REWRITEBASEPATH
              value: 'true'
            - name: LOGGING_VERBOSE
              value: 'true'
            - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  key: encryptedSavedObjects.key
                  name: kibana-key
            - name: XPACK_REPORTING_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  key: reporting.key
                  name: kibana-key
            - name: XPACK_SECURITY_ENCRYPTIONKEY
              valueFrom:
                secretKeyRef:
                  key: security.key
                  name: kibana-key
          image: docker.elastic.co/kibana/kibana:9.2.4
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 5601
            timeoutSeconds: 5
          name: kibana
          ports:
            - containerPort: 5601
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 120
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 5601
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 400m
              memory: 2536Mi
            requests:
              cpu: 150m
              memory: 600Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: private-nodegroup
          operator: Exists
