```
三主三从
7001-7003 主
7004-7006 从
[root@test cluster]# tree -f
.
├── ./docker-compose.yml
├── ./node_7001
│   ├── ./node_7001/conf
│   │   └── ./node_7001/conf/redis.conf
│   └── ./node_7001/data
│       ├── ./node_7001/data/appendonly.aof
│       ├── ./node_7001/data/dump.rdb
│       └── ./node_7001/data/nodes-7001.conf
├── ./node_7002
│   ├── ./node_7002/conf
│   │   └── ./node_7002/conf/redis.conf
│   └── ./node_7002/data
│       ├── ./node_7002/data/appendonly.aof
│       ├── ./node_7002/data/dump.rdb
│       └── ./node_7002/data/nodes-7002.conf
├── ./node_7003
│   ├── ./node_7003/conf
│   │   └── ./node_7003/conf/redis.conf
│   └── ./node_7003/data
│       ├── ./node_7003/data/appendonly.aof
│       ├── ./node_7003/data/dump.rdb
│       └── ./node_7003/data/nodes-7003.conf
├── ./node_7004
│   ├── ./node_7004/conf
│   │   └── ./node_7004/conf/redis.conf
│   └── ./node_7004/data
│       ├── ./node_7004/data/appendonly.aof
│       ├── ./node_7004/data/dump.rdb
│       └── ./node_7004/data/nodes-7004.conf
├── ./node_7005
│   ├── ./node_7005/conf
│   │   └── ./node_7005/conf/redis.conf
│   └── ./node_7005/data
│       ├── ./node_7005/data/appendonly.aof
│       ├── ./node_7005/data/dump.rdb
│       └── ./node_7005/data/nodes-7005.conf
├── ./node_7006
│   ├── ./node_7006/conf
│   │   └── ./node_7006/conf/redis.conf
│   └── ./node_7006/data
│       ├── ./node_7006/data/appendonly.aof
│       ├── ./node_7006/data/dump.rdb
│       └── ./node_7006/data/nodes-7006.conf
└── ./redis.conf

```

```
version: "3"

# 定义服务，可以多个
services:
  redis-7001: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7001 # 容器名称
    restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7001/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7001/data:/data
    ports:
      - 7001:7001
      - 17001:17001
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7002: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7002 # 容器名称
restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7002/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7002/data:/data
    ports:
      - 7002:7002
      - 17002:17002
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7003: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7003 # 容器名称
    restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7003/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7003/data:/data
    ports:
      - 7003:7003
      - 17003:17003
 command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7004: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7004 # 容器名称
    restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7004/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7004/data:/data
    ports:
      - 7004:7004
      - 17004:17004
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7005: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7005 # 容器名称
    restart: always # 容器总是重新启动
 volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7005/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7005/data:/data
    ports:
      - 7005:7005
      - 17005:17005
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7006: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7006 # 容器名称
    restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7006/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7006/data:/data
    ports:
      - 7006:7006
      - 17006:17006
    command:
 - /data/redis/cluster/node_7005/data:/data
    ports:
      - 7005:7005
      - 17005:17005
    command:
      redis-server /usr/local/etc/redis/redis.conf

  redis-7006: # 服务名称
    image: redis:5.0.10  # 创建容器时所需的镜像
    container_name: redis-7006 # 容器名称
    restart: always # 容器总是重新启动
    volumes: # 数据卷，目录挂载
      - /data/redis/cluster/node_7006/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/cluster/node_7006/data:/data
    ports:
      - 7006:7006
      - 17006:17006
    command:
      redis-server /usr/local/etc/redis/redis.conf
```

```
port 7001
cluster-enabled yes
cluster-config-file nodes-7001.conf
cluster-node-timeout 5000
appendonly yes
protected-mode no
requirepass 123456
masterauth 123456
cluster-announce-ip 172.26.24.77
cluster-announce-port 7001
cluster-announce-bus-port 17001
```

```
port 7004
cluster-enabled yes
cluster-config-file nodes-7004.conf
cluster-node-timeout 5000
appendonly yes
protected-mode no
requirepass 123456
masterauth 123456
cluster-announce-ip 172.26.24.77
cluster-announce-port 7004
cluster-announce-bus-port 17004
```
